# Basics
DESIGN_NAME: ariane
VERILOG_FILES: dir::src/*.v

# Basic clock def (matches sdc)
CLOCK_PORT: clk_i
CLOCK_PERIOD: 4

# SDC
PNR_SDC_FILE: dir::ariane.sdc
SIGNOFF_SDC_FILE: dir::ariane.sdc

# Reference fakeram macros (no gds?)
EXTRA_LEFS:
  - dir::lef/fakeram130_256x16.lef

EXTRA_LIBS:
  - dir::lib/fakeram130_256x16.lib

# Floorplan
DIE_AREA: [0, 0, 1500, 1500]
CORE_AREA: [10, 12, 1448, 1448]

# Default target density is at ~60%, which is too high
PL_TARGET_DENSITY_PCT: 45

FP_MACRO_HORIZONTAL_HALO: 65
FP_MACRO_VERTICAL_HALO: 65

# All of them are hooked up to VPWR/VGND (default power and ground nets)
# TODO: check power connections of stdcells?
"PDN_MACRO_CONNECTIONS": [
  ".*macro.* VPWR VGND VDD VSS"
]

# Extra RTL_MP Settings
RTLMP_MAX_INST: 30000
RTLMP_MIN_INST: 5000
RTLMP_MAX_MACRO: 16
RTLMP_MIN_MACRO: 4

# Copied over from the original config.mk, not sure why they're set
SYNTH_HIERARCHY_MODE: keep
PL_RESIZER_GATE_CLONING: false

# Other strategy would explode synth times, this is closest to ORFS
SYNTH_STRATEGY: AREA 3

# TODO: pin cfg
# export PLACE_PINS_ARGS = -exclude left:0-500 -exclude left:1000-1500: -exclude right:* -exclude top:* -exclude bottom:*

# TODO: Fix duplicate declaration errors? Linter isn't happy but it still works..
RUN_LINTER: false

# Yosys will complain about a few nets with no driver
ERROR_ON_SYNTH_CHECKS: false
